version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    allow:
      - dependency-name: 'eslint*'
      - dependency-name: '@typescript-eslint*'
      - dependency-name: '@babel*'
      - dependency-name: 'prettier'
